config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users #includes users/sign_in, users/sign_out, users/password/new, etc.;
  
  root "pages#index"
  
  get 'pages', to: 'pages#index'
  get 'pages/index'
  
  resources :entities
  resources :events
  #resources :entities_events
  


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  
  has_many :entities_events
  has_many :events, through: :entities_events
  
  has_many :relationship_left, class_name: 'Relationship', foreign_key: 'left_id'
  has_many :relationship_right, class_name: 'Relationship', foreign_key: 'right_id'
  
  validates_presence_of :name, :user
 
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  include AuthorizationConcern

  def index
    @entities = Entity.all.select { |x| x.user_id == current_user.id }
  end
  
  def show
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.user_id = current_user.id

    if @entity.save
      redirect_to @entity
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @entity.update(entity_params)
      redirect_to @entity
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @entity.destroy
    redirect_to entities_path, status: :see_other
  end

  private

  def get_record
    @entity = Entity.find(params[:id])
    check_ownership(@entity)
  end

  def entity_params
    params.require(:entity).permit(:name, :about)
  end

end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.erb
<%= form_with model: @entity do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @entity.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<hr align="left" width="40%">
  <div>
    <%= form.label :about %><br>
    <%= form.text_area :about %>
    <% @entity.errors.full_messages_for(:about).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<hr align="left" width="40%">
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entities/edit.html.erb
<h1>Edit Entity</h1>

<%= render "form", entity: @entity %>

app/views/entities/index.html.erb
<h1>Entities</h1>
<h2>People, Places, & Things, Oh My!</h2>

<ul>
  <% @entities.each do |e| %>
    <li>
      <a href="/entities/<%= e.id %>">
      <%= e.name %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Entity', new_entity_path %>
</br><%= link_to 'Home', pages_path %>

app/views/entities/new.html.erb
<h1>New Entity</h1>

<%= render "form", entity: @entity %>

app/views/entities/show.html.erb
<h1><%= @entity.name %></h1>
<p><%= @entity.about %></p>

</br><%= link_to 'Edit', edit_entity_path(@entity) %>
</br><%= link_to 'Delete', entity_path(@entity), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</br><%= link_to 'Return to Entities List', entities_path %>