config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users #includes users/sign_in, users/sign_out, users/password/new, etc.;
  
  root "pages#index"
  
  get 'pages', to: 'pages#index'
  get 'pages/index'
  
  resources :entities
  resources :events
  #resources :entities_events
  


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  
  has_many :entities_events
  has_many :entities, through: :entities_events
  
  validates_presence_of :name, :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include AuthorizationConcern

  def index
    @events = Event.all.select { |x| x.user_id == current_user.id }
  end
  
  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, status: :see_other
  end

  private
  
  def get_record
    @event = Entity.find(params[:id])
    check_ownership(@event)
  end

  def event_params
    params.require(:event).permit(:name, :story)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
    <% @event.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<hr align="left" width="40%">
  <div>
    <%= form.label :story %><br>
    <%= form.text_area :story %><br>
    <% @event.errors.full_messages_for(:story).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<hr align="left" width="40%">
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", entity: @event %>

app/views/events/index.html.erb
<h1>Events</h1>

<ul>
  <% @events.each do |e| %>
    <li>
      <a href="/events/<%= e.id %>">
      <%= e.name %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Event', new_event_path %>
</br><%= link_to 'Home', pages_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p><%= @event.story %></p>

</br><%= link_to 'Edit', edit_event_path(@event) %>
</br><%= link_to 'Delete', event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</br><%= link_to 'Return to Events List', events_path %>